CREATE DATABASE IF NOT EXISTS accident_project;
USE accident_project;

DROP TABLE ACCIDENT_2009;
CREATE EXTERNAL TABLE ACCIDENT_2009 
(
CASENUM INT,  
SPDLIM_H INT,
HOUR_IM INT,
MINUTE_IM INT,
RELJCT_IM INT,
ALIGN_IM INT,
PROFIL_IM INT,
SURCON_IM INT,
TRFCON_IM INT,
LGTCON_IM INT,
WEATHR_IM INT,
MANCOL_IM INT,
EVENT1_IM INT,
WEIGHT INT,
MONTH INT,
DAY_WEEK INT,
REGION INT,
MAN_COLL INT,
INT_HWY INT,
RELJCT1 INT,
REL_ROAD INT,
LGT_COND INT,
WEATHER INT,
SCH_BUS INT,
WRK_ZONE INT,
ALCOHOL INT,
HARM_EV INT,
MAX_SEV INT,
STRATUM INT,
TRAF_WAY INT,
SUR_COND INT,
PROFILE INT,
ALIGNMNT INT,
TRAF_CON INT,
HOUR INT,
MINUTE INT,
PERNOTMVIT INT,
NUM_INJ INT,
NO_LANES INT,
PED_ACC INT,
PJ INT,
PSU INT,
PSUSTRAT INT,
PVH_INVL INT,
SP_LIMIT INT,
VE_FORMS INT,
YEAR INT,
WKDY_IM INT,
MAXSEV_IM INT,
NO_INJ_IM INT,
ALCHL_IM INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/ACCIDENT';

--############################################################




DROP TABLE VEHICLE_2009;
CREATE EXTERNAL TABLE VEHICLE_2009 
(
CASENUM INT,  
VEH_NO INT,  
HITRUN_IM INT,  
BDYTYP_IM INT,  
MDLYR_IM INT,  
IMPACT1_IM INT,  
VEVENT_IM INT,  
PCRASH1_IM INT,  
MXVSEV_IM INT,  
NUMINJ_IM INT,  
V_ALCH_IM INT,  
WEIGHT INT,  
REGION INT,  
STRATUM INT,  
PJ INT,  
PSU INT,  
PSUSTRAT INT,  
VE_FORMS INT,  
NUMOCCS INT,  
MONTH INT,  
HOUR INT,  
MINUTE INT,  
HARM_EV INT,  
MAN_COLL INT,  
UNITTYPE INT,  
HIT_RUN INT,  
MAKE INT,  
MODEL INT,  
BODY_TYP INT,  
MOD_YEAR INT,  
VIN varchar(500),  
TOW_VEH INT,  
J_KNIFE INT,  
MCARR_I1 varchar(500),  
MCARR_I2 varchar(500),  
MCARR_ID varchar(500),  
GVWR INT,  
V_CONFIG INT,  
CARGO_BT INT,  
HAZ_INV INT,  
HAZ_PLAC INT,  
HAZ_ID INT,  
HAZ_CNO INT,  
HAZ_REL INT,  
BUS_USE INT,  
SPEC_USE INT,  
EMER_USE INT,  
TRAV_SP INT,  
ROLLOVER INT,  
ROLINLOC INT,  
IMPACT1 INT,  
DEFORMED INT,  
TOWED INT,  
M_HARM INT,  
VEH_SC1 INT,  
VEH_SC2 INT,  
VEH_ALCH INT,  
MAX_VSEV INT,  
NUM_INJV INT,  
FIRE_EXP INT,  
DR_PRES INT,  
DR_ZIP varchar(500),  
SPEEDREL INT,  
DR_SF1 INT,  
DR_SF2 INT,  
DR_SF3 INT,  
DR_SF4 INT,  
VTRAFWAY INT,  
VNUM_LAN INT,  
VSPD_LIM INT,  
VALIGN INT,  
VPROFILE INT,  
VSURCOND INT,  
VTRAFCON INT,  
VTCONT_F INT,  
P_CRASH1 INT,  
P_CRASH2 INT,  
P_CRASH3 INT,  
PCRASH4 INT,  
PCRASH5 INT,  
ACC_TYPE INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/VEHICLE';  

 

