CREATE DATABASE IF NOT EXISTS accident_project;
USE accident_project;

DROP TABLE ACCIDENT_2009;
CREATE EXTERNAL TABLE ACCIDENT_2009 
(
CASENUM INT,
SPDLIM_H INT,
HOUR_I INT,
MINUTE_I INT,
RELJCT_I INT,
ALIGN_I INT,
PROFIL_I INT,
SURCON_I INT,
TRFCON_I INT,
LGTCON_I INT,
WEATHR_I INT,
MANCOL_I INT,
EVENT1_I INT,
WEIGHT INT,
MONTH INT,
DAY_WEEK INT,
REGION INT,
MAN_COL INT,
INT_HWY INT,
REL_JCT INT,
REL_ROAD INT,
LGT_COND INT,
WEATHER INT,
SCH_BUS INT,
WRK_ZONE INT,
ALCOHOL INT,
EVENT1 INT,
MAX_SEV INT,
STRATUM INT,
TRAF_WAY INT,
SUR_COND INT,
PROFILE INT,
ALIGNMNT INT,
TRAF_CON INT,
HOUR INT,
MINUTE INT,
NON_INVL INT,
NUM_INJ INT,
NO_LANES INT,
PED_ACC INT,
PJ INT,
PSU INT,
PSUSTRAT INT,
PVH_INVL INT,
SP_LIMIT INT,
VEH_INVL INT,
YEAR INT,
WKDY_I INT,
MAXSEV_I INT,
NO_INJ_I INT,
ALCHL_I INT


)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/ACCIDENT';

DROP TABLE VEHICLE_2009;
CREATE EXTERNAL TABLE VEHICLE_2009 
(
CASENUM INT,  
VEHNO INT,  
BDYTYP_H INT,  
VIN varchar(500),  
WEIGHT INT,  
HAZ_ID INT,  
MODEL_YR INT,  
DAM_AREA INT,  
DZIPCODE varchar(500),  
CARIDNUM INT,  
REGION INT,  
HIT_RUN INT,  
MAKE INT,  
BODY_TYP INT,  
SPEC_USE INT,  
EMER_USE INT,  
TOW_VEH INT,  
JACKNIFE INT,  
FIRE_EXP INT,  
VTRAFCON INT,  
DEFORMED INT,  
TOWED INT,  
P_CRASH1 INT,  
VEH_ROLE INT,  
ACC_TYPE INT,  
IMPACT INT,  
P_CRASH3 INT,  
PCRASH4 INT,  
PCRASH5 INT,  
TRAV_SP INT,  
ROLLOVER INT,  
CARGO_BT INT,  
HAZ_PLAC INT,  
HAZ_REL INT,  
DR_PRES INT,  
SPEEDREL INT,  
VSURCOND INT,  
VPROFILE INT,  
VALIGN INT,  
VTRAFWAY INT,  
V_EVENT INT,  
VEH_ALCH INT,  
MAX_VSEV INT,  
STRATUM INT,  
NUMOCCS INT,  
DR_DSTRD INT,  
FACTOR INT,  
VIOLATN INT,  
VIS_OBSC INT,  
DRMAN_AV INT,  
ROLINLOC INT,  
HAZ_INV INT,  
HAZ_CNO INT,  
MHENUM INT,  
MODEL INT,  
NUM_INJV INT,  
VNUM_LAN INT,  
OCC_INVL INT,  
PJ INT,  
PSU INT,  
PSUSTRAT INT,  
P_CRASH2 INT,  
VSPD_LIM INT,  
IMPACT_H INT,  
VROLE_I INT,  
V_EVNT_H INT,  
MDLYR_I INT,  
MANEUV_I INT,  
VLTN_I INT,  
HITRUN_I INT,  
MXVSEV_I INT,  
NUMINJ_I INT,  
V_ALCH_I INT

)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/VEHICLE';  


DROP TABLE PERSON_2009;
CREATE EXTERNAL TABLE PERSON_2009 
(
CASENUM INT,  
PERNO INT,  
VEHNO INT,  
AGE_H INT,  
SEX_H INT,  
INJSEV_H INT,  
SEAT_H INT,  
PERALC_H INT,  
WEIGHT INT,  
PER_TYP INT,  
SEAT_POS INT,  
EJECTION INT,
SEX INT,  
INJ_SEV INT,  
HOSPITAL INT,  
PER_ALCH INT,  
PER_DRUG INT,  
LOCATN INT,  
AIR_BAG INT,  
REGION INT,  
REST_SYS INT,  
STRATUM INT,  
IMPAIRMT INT,
ACTION INT,  
SAF_EQMT INT,  
ALCHTEST INT,  
ALTSTYPE INT,  
ALTRSULT INT,  
DRUGTEST INT,  
DRTSTYPE INT,  
DRTRSULT INT,  
AGE INT,  
PJ INT,  
PSU INT,  
PVEHNO INT,  
STR_VEH INT,  
EJECT_I INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/PERSON';



DROP TABLE DISTRACT_2009;
CREATE EXTERNAL TABLE DISTRACT_2009 
(
MDRDSTRD INT,  
REGION INT,  
STRATUM INT,  
CASENUM INT,  
WEIGHT INT,  
PJ INT,  
PSU INT,  
VEHNO INT

)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2009/DISTRACT';