CREATE DATABASE IF NOT EXISTS accident_project;
USE accident_project;

DROP TABLE ACCIDENT_2010;
CREATE EXTERNAL TABLE ACCIDENT_2010 
(
CASENUM INT,  
WKDY_IM INT,  
MANCOL_IM INT,  
LGTCON_IM INT,  
WEATHR_IM INT,  
RELJCT1_IM INT,  
RELJCT2_IM INT,  
HOUR_IM INT,  
MINUTE_IM INT,  
EVENT1_IM INT,  
MAXSEV_IM INT,  
NO_INJ_IM INT,  
ALCHL_IM INT,  
WEIGHT INT,  
MONTH INT,  
DAY_WEEK INT,  
REGION INT,  
LAND_USE INT,  
MAN_COL INT,  
INT_HWY INT,  
REL_ROAD INT,  
LGT_COND INT,  
WEATHER INT,  
SCH_BUS INT,  
WRK_ZONE INT,  
ALCOHOL INT,  
EVENT1 INT,  
MAX_SEV INT,  
STRATUM INT,  
RELJCT1 INT,  
RELJCT2 INT,  
WEATHER1 INT,  
WEATHER2 INT,  
TYP_INT INT,  
HOUR INT,  
MINUTE INT,  
NON_INVL INT,  
NUM_INJ INT,  
PJ INT,  
PSU INT,  
PSUSTRAT INT,  
PVH_INVL INT,  
VEH_INVL INT,  
YEAR INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2010/ACCIDENT';




DROP TABLE VEHICLE_2010;
CREATE EXTERNAL TABLE VEHICLE_2010 
(
CASENUM INT,  
MDLYR_IM INT,  
HITRUN_IM INT,  
BDYTYP_IM INT,  
PCRASH1_IM INT,  
IMPACT1_IM INT,  
VEHNO INT,  
VEVENT_IM INT,  
MXVSEV_IM INT,  
NUMINJ_IM INT,  
V_ALCH_IM INT,  
VIN varchar(500),  
WEIGHT INT,  
HAZ_ID INT,  
MODEL_YR INT,  
DZIPCODE varchar(500),  
MCARR_ID INT,  
REGION INT,  
HIT_RUN INT,  
MAKE INT,  
BODY_TYP INT,  
SPEC_USE INT,  
EMER_USE INT,  
TOW_VEH INT,  
JACKNIFE INT,  
FIRE_EXP INT,  
VTRAFCON INT,  
DEFORMED INT,  
TOWED INT,  
P_CRASH1 INT,  
ACC_TYPE INT,  
IMPACT1 INT,  
P_CRASH3 INT,  
PCRASH4 INT,  
PCRASH5 INT,  
TRAV_SP INT,  
ROLLOVER INT,  
CARGO_BT INT,  
HAZ_PLAC INT,  
HAZ_REL INT,  
DR_PRES INT,  
SPEEDREL INT,  
VSURCOND INT,  
VPROFILE INT,  
VALIGN INT,  
VTRAFWAY INT,  
V_EVENT INT,  
VEH_ALCH INT,  
MAX_VSEV INT,  
STRATUM INT,  
NUMOCCS INT,  
ROLINLOC INT,  
HAZ_INV INT,  
HAZ_CNO INT,  
VTCONT_F INT,  
IMPACT2 INT,  
BUS_USE INT,  
V_CONFIG INT,  
MHENUM INT,  
MODEL INT,  
NUM_INJV INT,  
OCC_INVL INT,  
P_CRASH2 INT,  
PJ INT,  
PSU INT,  
PSUSTRAT INT,  
VNUM_LAN INT,  
VSPD_LIM INT

)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2010/VEHICLE';  

DROP TABLE PERSON_2010;
CREATE EXTERNAL TABLE PERSON_2010 
(
CASENUM INT,  
VEHNO INT,  
PERNO INT,  
EJECT_IM INT,  
SEX_IM INT,  
INJSEV_IM INT,  
PERALCH_IM INT,  
SEAT_IM INT,  
AGE_IM INT,  
WEIGHT INT,  
PER_TYP INT,  
SEAT_POS INT,  
EJECTION INT,  
SEX INT,  
INJ_SEV INT,  
HOSPITAL INT,  
PER_ALCH INT,  
PER_DRUG INT,  
LOCATN INT,  
AIR_BAG INT,  
REGION INT,  
REST_SYS INT,  
STRATUM INT,  
ALCHTEST INT,  
ALTSTYPE INT,  
ALTRSULT INT,  
DRUGTEST INT,  
AGE INT,  
DRTSTYPE INT,  
DRTRSULT INT,  
REST_MIS INT,  
PJ INT,  
PSU INT,  
PVEHNO INT,  
STR_VEH INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2010/PERSON';



DROP TABLE DISTRACT_2010;
CREATE EXTERNAL TABLE DISTRACT_2010 
(
MDRDSTRD INT,  
REGION INT,  
STRATUM INT,  
CASENUM INT,  
WEIGHT INT,  
PJ INT,  
PSU INT,  
VEHNO INT

)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = "\t",
   "quoteChar"     = '"',
   "escapeChar"    = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/accident_project/2010/DISTRACT';
